# Generated by Django 3.2.3 on 2021-06-17 19:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210610_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
